**Project 1: Grayscale and color image**

# Công thức 
## Chuyển đổi từ ảnh màu sang ảnh xám
Với grayscale là giá trị của pixel ảnh xám, còn R, G, B là các giá trị pixel ảnh màu tương ứng, ta có:
- Công thức với các trọng số:
$$
    Grayscale = 0.299R + 0.587G + 0.114B
$$
- Công thức lấy giá trị trung bình:
$$
    Grayscale = \frac{R + G + B}{3}
$$
## Chuyển đổi từ ảnh xám thành ảnh màu
Vì không có công thức cụ thể cho việc kết hợp màu nên ở bài này, tôi sẽ thực hiện lấy giá trị grayscale của công thức với các trọng số nhân với trọng số bất kì và thực hiện lấy phần dư với 255 làm giá trị pixel cho ảnh màu R, G, B.
Với 
$$
    Grayscale = 0.299R + 0.587G + 0.114B
$$
Thì mỗi pixel trong ảnh được chuyển thành ảnh màu sẽ có giá trị px: (a x Grayscale, b x Grayscale, c x Grayscale)


# Hiện thực

Chuyển đổi ảnh màu thành ảnh xám

In [10]:
import cv2
import numpy as np

In [16]:
#show original image
original_img = cv2.imread("cat.jpg")
print(original_img)
# cv2.imshow("original image", original_img)
# cv2.waitKey(0) 
# cv2.destroyAllWindows() 

[[[231 144  70]
  [231 144  70]
  [231 145  69]
  ...
  [ 30  33  18]
  [ 33  33  19]
  [ 34  34  22]]

 [[230 143  69]
  [230 144  68]
  [230 144  68]
  ...
  [ 30  33  18]
  [ 32  32  18]
  [ 32  32  20]]

 [[230 144  68]
  [230 144  68]
  [230 144  68]
  ...
  [ 30  33  18]
  [ 31  31  19]
  [ 30  30  18]]

 ...

 [[ 14  31  18]
  [ 14  31  18]
  [ 14  31  18]
  ...
  [ 51 111  87]
  [ 59 120  94]
  [ 62 123  97]]

 [[ 14  31  18]
  [ 14  31  18]
  [ 14  31  18]
  ...
  [ 59 120  92]
  [ 64 125  97]
  [ 64 126  96]]

 [[ 14  31  18]
  [ 14  31  18]
  [ 14  31  18]
  ...
  [ 64 128  98]
  [ 67 131 101]
  [ 67 130  98]]]


In [21]:
r,g,b = original_img[:,:,0], original_img[:,:,1], original_img[:,:,2]

117.94


In [15]:
#công thức với các trọng số
gray_1 = .299 * r + .587 * g + .114 * b
weighted_gray = gray_1.astype(np.uint8)
print(weighted_gray)
cv2.imshow("weighted grayscale image", weighted_gray)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

[[161 161 162 ...  30  31  32]
 [160 161 161 ...  30  30  30]
 [161 161 161 ...  30  29  28]
 ...
 [ 24  24  24 ...  90  98 101]
 [ 24  24  24 ...  98 103 104]
 [ 24  24  24 ... 105 108 107]]


In [14]:
#công thức trung bình
gray_2 = (r+g+b)/3
average_grayscale = gray_2.astype(np.uint8)
print(average_grayscale)
cv2.imshow("weighted grayscale image", average_grayscale)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

[[63 63 63 ... 27 28 30]
 [62 62 62 ... 27 27 28]
 [62 62 62 ... 27 27 26]
 ...
 [21 21 21 ... 83  5  8]
 [21 21 21 ...  5 10 10]
 [21 21 21 ... 11 14 13]]


Chuyển đổi ảnh xám thành ảnh màu

In [28]:
# tạo ảnh màu với a, b, c = (20/mean, 30/mean, 50/mean) với mean là trung bình các giá trị trong ma trận Grayscale
# với a, b, c = (1,1,1), out_put sẽ là ảnh màu tương đương với ảnh xám
img_out = np.empty_like(original_img, dtype=np.uint8)
mean = np.mean(gray_1)
print(mean)
img_out[:, :, 0] = np.minimum(gray_1*20/mean,255).astype(np.uint8)
img_out[:, :, 1] = np.minimum(gray_1*30/mean,255).astype(np.uint8)
img_out[:, :, 2] = np.minimum(gray_1*50/mean,255).astype(np.uint8)
print(img_out)
cv2.imshow("colored image", img_out)
cv2.waitKey(0) 
cv2.destroyAllWindows() 

87.58151079234175
[[[110  55  92]
  [110  55  92]
  [111  55  92]
  ...
  [ 20  10  17]
  [ 21  10  17]
  [ 22  11  18]]

 [[109  54  91]
  [110  55  91]
  [110  55  91]
  ...
  [ 20  10  17]
  [ 20  10  17]
  [ 20  10  17]]

 [[110  55  91]
  [110  55  91]
  [110  55  91]
  ...
  [ 20  10  17]
  [ 20  10  16]
  [ 19   9  16]]

 ...

 [[ 16   8  13]
  [ 16   8  13]
  [ 16   8  13]
  ...
  [ 61  30  51]
  [ 67  33  56]
  [ 69  34  58]]

 [[ 16   8  13]
  [ 16   8  13]
  [ 16   8  13]
  ...
  [ 67  33  56]
  [ 70  35  59]
  [ 71  35  59]]

 [[ 16   8  13]
  [ 16   8  13]
  [ 16   8  13]
  ...
  [ 72  36  60]
  [ 74  37  61]
  [ 73  36  61]]]
